# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodire', '0001_initial'),
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='dire_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodire.Pro_icon', verbose_name='\u76ee\u5f55\u56fe\u6807'),
        ),
    ]
