# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.File')),
                ('videourl', models.URLField()),
                ('default_alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u89c6\u9891\u4e0d\u5b58\u5728')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
            bases=('filer.file',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
