# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='default_alt_text',
        ),
    ]
