# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_default_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videourl',
            field=models.URLField(blank=True, null=True, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
