# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SclMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=50, verbose_name='OpenId')),
                ('user_phone', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7')),
                ('customerclass', models.CharField(max_length=20, verbose_name='\u5165\u53e3\u5e73\u53f0')),
            ],
        ),
    ]
