# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0008_folder_dire_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('everybody', models.BooleanField(default=False, verbose_name='everybody')),
                ('can_edit', models.SmallIntegerField(blank=True, choices=[(1, 'allow'), (0, 'deny')], default=None, null=True, verbose_name='can edit')),
                ('can_read', models.SmallIntegerField(blank=True, choices=[(1, 'allow'), (0, 'deny')], default=None, null=True, verbose_name='can read')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='file')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filer_file_permissions', to='auth.Group', verbose_name='group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filer_file_permissions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'file permission',
                'verbose_name_plural': 'file permissions',
            },
        ),
    ]
